name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Use local action (dogfooding)
      - uses: aaronsteers/semantic-pr-release-drafter@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # The following config is commented out because it now matches the defaults.
        # It is kept here as an example of how to customize the action.
        # with:
        #   name-template: 'v$RESOLVED_VERSION'
        #   tag-template: 'v$RESOLVED_VERSION'
        #   template: |
        #     $CHANGES
        #
        #     ---
        #
        #     **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
        #   change-template: '* $TITLE ($URL) $SHA'
        #   categories: |
        #     - title: '‚ö†Ô∏è Breaking Changes'
        #       commit-types:
        #         - 'breaking'
        #     - title: '‚ú® New Features'
        #       commit-types:
        #         - 'feat'
        #     - title: 'üêõ Bug Fixes'
        #       commit-types:
        #         - 'fix'
        #     - title: '‚ñ≤ Other Changes'
        #       collapse-after: 2
        #       commit-types:
        #         - 'refactor'
        #         - 'perf'
        #         - 'style'
        #     - title: 'üìñ Documentation'
        #       collapse-after: 2
        #       commit-types:
        #         - 'docs'
        #     - title: '‚öôÔ∏è Under the Hood'
        #       collapse-after: 2
        #       commit-types:
        #         - 'chore'
        #         - 'ci'
        #         - 'build'
        #         - 'test'
